name: Create python Exe to Release

on: 
  push:
    branches:
      - 'master'
    paths:
      - 'bfi.py'

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Build and Release
        uses: kentsx/Python2Exe@v1.1.1
        with:
          main: master
          exe_name: 'My Executable'
          icon: 'application.ico'
          artifact: false
          release: true
          tag: steps.version.outputs.version
