name: Create python Exe to Release

on: 
  push:
    branches:
      - 'master'

jobs:
  pyinstaller-build:
    runs-on: windows-latest
    steps:
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        - name: Print Version
          run: echo "Git version is ${{ steps.version.outputs.version }}"

      - name: Build and Release
        uses: kentsx/Python2Exe@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          main: bif
          python_version: 3.12
          pyinstaller_version: 6.11.1
          exe_name: 'bif'
          icon: 'application.ico'
          artifact: true
          release: true
          tag: ${{ steps.version.outputs.version }}
          
