name: Package Application with Pyinstaller

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@main
      with:
        path: bif.py

    - uses: actions/upload-artifact@v4
      with:
        name: basic-info-file-retriever
        path: dist/bif.exe
    - name: Publish Release (Release)
      uses: softprops/action-gh-release@v2
      with:

          name: basic-info-file-retriever
          draft: false
          prerelease: false
          files: dist/bif.exe
    
