name: Create python Exe to Release

on: 
  push:
    branches:
      - 'main'

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Semantic Versions
        id: semver
        uses: ablil/semantic-versioning@v0.1.0

      - name: Print Version
        run: echo "Git version is ${{ steps.semver.outputs.version }}"
    outputs:
      version: ${{ steps.semver.outputs.version }}

  pyinstaller-build:
    needs: versioning
    runs-on: windows-latest
    steps:
      - name: Build and Release
        uses: kentsx/Python2Exe@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          main: bif
          python_version: 3.12
          pyinstaller_version: 6.11.1
          exe_name: 'bif'
          icon: 'application.ico'
          artifact: true
          release: true
          tag: ${{ needs.versioning.outputs.version }}

  edit_release:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Edit Release
        uses: irongut/EditRelease@v1.2.0
        with:
          name: "Basic Info File Retriever ${{ needs.versioning.outputs.version }}"
          replacename: true
      
          